source "https://rubygems.org"

gem 'activerecord', '~>5.2.3'
gem 'sinatra-activerecord'
gem 'rake'
gem 'sqlite3', '~> 1.3.6'
gem 'pry'
gem 'require_all'
gem 'rack'
gem 'shotgun'
gem 'sinatra'
gem 'rest-client'
gem 'byebug'
