# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'pry'
# gem "rails"
gem "sqlite3", "~> 1.4.0"
gem 'rake'
# gem 'require_all'
gem 'activerecord', "~>5.2.3"
gem 'sinatra-activerecord'
# gem 'rest-client'